### ISSUE TITLE
RuntimeError: Tensors of type TensorImpl do not have sizes

### ISSUE THREAD

**Issue by Tomzxcv** [zhengyuf/PointAvatar#13]
I use torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 functorch==0.2.0 pytorch3d==0.6.2. get some error.
Is the pytorch3d version not correct?

Traceback (most recent call last):
  File "/home/hmli/NeRF/PointAvatar/code/scripts/exp_runner.py", line 37, in <module>
    runner.run()
  File "/home/hmli/NeRF/PointAvatar/code/scripts/train.py", line 325, in run
    model_outputs = self.model(model_input)
  File "/home/hmli/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hmli/NeRF/PointAvatar/code/../code/model/point_avatar_model.py", line 176, in forward
    images = self._render(transformed_point_cloud, cameras)
  File "/home/hmli/NeRF/PointAvatar/code/../code/model/point_avatar_model.py", line 92, in _render
    fragments = rasterizer(point_cloud)
  File "/home/hmli/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hmli/NeRF/pytorch3d/pytorch3d/renderer/points/rasterizer.py", line 132, in forward
    idx, zbuf, dists2 = rasterize_points(
  File "/home/hmli/NeRF/pytorch3d/pytorch3d/renderer/points/rasterize_points.py", line 142, in rasterize_points
    return _RasterizePoints.apply(
  File "/home/hmli/NeRF/pytorch3d/pytorch3d/renderer/points/rasterize_points.py", line 223, in forward
    idx, zbuf, dists = _C.rasterize_points(*args)
RuntimeError: Tensors of type TensorImpl do not have sizes

**Comment by zhengyuf** [comment]
Hi, please check readme for pytorch3d
version.
