### ISSUE TITLE
pytorch3d error

### ISSUE THREAD

**Issue by HyunsooCha** [zhengyuf/PointAvatar#3]
Hi

Thank you for your excellent work.
To install pytorch3d in your repository, I've got this message:

$ git clone git@github.com:zhengyuf/pytorch3d.git
Cloning into 'pytorch3d'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

So, I installed your modified version of pytorch3d like this:

git clone https://github.com/zhengyuf/pytorch3d.git
git checkout point-avatar
pip install -e .

However, when I trained the code, I got this error message:

Traceback (most recent call last):
  File "/root/GitHub/PointAvatar/code/scripts/exp_runner.py", line 35, in <module>
    runner.run()
  File "/root/GitHub/PointAvatar/code/../code/scripts/train.py", line 325, in run
    model_outputs = self.model(model_input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/GitHub/PointAvatar/code/../code/model/point_avatar_model.py", line 176, in forward
    images = self._render(transformed_point_cloud, cameras)
  File "/root/GitHub/PointAvatar/code/../code/model/point_avatar_model.py", line 92, in _render
    fragments = rasterizer(point_cloud)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/GitHub/pytorch3d/pytorch3d/renderer/points/rasterizer.py", line 132, in forward
    idx, zbuf, dists2 = rasterize_points(
  File "/root/GitHub/pytorch3d/pytorch3d/renderer/points/rasterize_points.py", line 142, in rasterize_points
    return _RasterizePoints.apply(
  File "/root/GitHub/pytorch3d/pytorch3d/renderer/points/rasterize_points.py", line 223, in forward
    idx, zbuf, dists = _C.rasterize_points(*args)
RuntimeError: Not compiled with GPU support

I used Docker because my server's cuda version is 12.0. When I built Dockerfile, there was no error message. The build was successful.
Also, I double-checked if there's something wrong related to Pytorch or Pytorch3D like this:

Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import pytorch3d
>>> torch.__version__
'1.11.0'
>>> torch.cuda.is_available()
True
>>> from pytorch3d import _C
>>>

Do you know how to solve this issue?
Thank you for your reply in advance.

**Comment by zhengyuf** [comment]
Maybe the pytorch3d is built without CUDA support?

https://github.com/facebookresearch/pytorch3d/issues/1161

**Comment by HyunsooCha** [comment]
Thanks for your reply
I solved this issue using this: ENV TORCH_CUDA_ARCH_LIST="8.6+PTX"

**Comment by Zvyozdo4ka** [comment]
@HyunsooCha Could you share docker image that you used and a little bit of instructructions how did you run this project, please?
