### ISSUE TITLE
pytorch3d

### ISSUE THREAD

**Issue by Zvyozdo4ka** [zhengyuf/PointAvatar#30]
hello.

I tried to follow[ instructions](https://pytorch.org/get-started/previous-versions/) to install your pytorch3d version. 
But still there are errors:
```
  File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
        super().run_command(command)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
        super().run_command(command)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
        _build_ext.run(self)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
        build_ext.build_extensions(self)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
        self._build_extensions_serial()
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        objects = self.compiler.compile(
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]
```

What cuda version do you have? Does anyone have a successful experience of installation? please share insights and your cuda version

**Comment by HaoDot** [comment]
same question!!!

**Comment by HaoDot** [comment]
> same question!!!

seem to work with cuda11.3

**Comment by Zvyozdo4ka** [comment]
> seem to work with cuda11.3

really? have you tested already?

**Comment by Zvyozdo4ka** [comment]
> > same question!!!
> 
> seem to work with cuda11.3

worked with cuda 11.7 in my case, but why it throws the error: 

```
Traceback (most recent call last):
  File "/media/yulduz/hdd/Projects/PointAvatar/code/scripts/exp_runner.py", line 29, in <module>
    runner = TrainRunner(conf=opt.conf,
  File "/media/yulduz/hdd/Projects/PointAvatar/code/scripts/train.py", line 104, in __init__
    self.model = PointAvatar(conf=self.conf.get_config('model'),
  File "/media/yulduz/hdd/Projects/PointAvatar/code/model/point_avatar_model.py", line 36, in __init__
    self.FLAMEServer(expression_params=self.FLAMEServer.canonical_exp, full_pose=self.FLAMEServer.canonical_pose)
  File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/yulduz/hdd/Projects/PointAvatar/code/flame/FLAME.py", line 127, in forward
    vertices, pose_feature, transformations = lbs(betas, full_pose, template_vertices,
  File "/media/yulduz/hdd/Projects/PointAvatar/code/flame/lbs.py", line 63, in lbs
    v_shaped = v_template + torch.einsum('bl,mkl->bmk', [betas, shapedirs])
  File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/functional.py", line 328, in einsum
    return einsum(equation, *_operands)
  File "/home/yulduz/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/functional.py", line 330, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

```

**Comment by zhengyuf** [comment]
It seems to be a problem with torch cuda version, does [this](https://github.com/hpcaitech/ColossalAI/issues/2759) help?
